name: flutter_countryify
description: A Flutter package to get country details (name, code, currency) and flag widgets in square, rounded, or circle shapes.
version: 0.0.2
homepage: https://github.com/hwasiq15/flutter_countryify
repository: https://github.com/hwasiq15/flutter_countryify
issue_tracker: https://github.com/hwasiq15/flutter_countryify/issues
license: MIT

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flags/